Add Heading component, setting default font style to white and Poppins
phlgr/moviescout pull request #10
Opened 2021-11-15 11:53 UTC by F-Kirchhoff

2021-11-15 13:56 UTC, marwinburesch requested changes
Good work!
A few comments though, and I'd also shorten the title and expand the PR description

2021-11-15 13:56 UTC, marwinburesch commented on src/app/components/Headlng/Heading.stories.tsx
> +export const Headline_Large = (): JSX.Element => (
"Headline" is already implied by the filename and line 6

2021-11-15 13:56 UTC, marwinburesch commented on src/app/components/Headlng/Heading.tsx
> +  size: string;
This could be a bit more restricted, maybe with a `|` :)

2021-11-15 13:56 UTC, marwinburesch commented on src/app/components/Headlng/Heading.tsx
> +  return size === 'large' ? <H1>{children}</H1> : <H2>{children}</H2>;
I think you could add some more options, you could use an object to store the JSX and return it based on a prop :)

2021-11-15 13:56 UTC, marwinburesch commented on src/app/components/Headlng/Heading.tsx
> +  font-size: 30px;
You should use a relative unit here

2021-11-15 14:59 UTC, F-Kirchhoff commented on src/app/components/Headlng/Heading.stories.tsx
> +export const Headline_Large = (): JSX.Element => (
really good tips! thanks

2021-11-16 11:25 UTC, F-Kirchhoff commented
Closes #5

2021-11-16 11:44 UTC, marwinburesch approved these changes
awesome thank you :) 🐜

2021-11-16 11:44 UTC, marwinburesch commented on src/app/components/Typography/Typography.tsx
> +`;
An empty line after each component would be more readable

2021-11-16 13:47 UTC, marwinburesch approved these changes
yay

2021-11-16 13:47 UTC, merged